"""Added configuration table

Revision ID: 3b0e11deb418
Revises: b1d030a823a8
Create Date: 2026-02-18 14:04:55.810548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0e11deb418'
down_revision = 'b1d030a823a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('configId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creationDate', sa.Date(), nullable=False),
    sa.Column('lastUpdate', sa.Date(), nullable=False),
    sa.Column('createdBy', sa.Integer(), nullable=False),
    sa.Column('updatedBy', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['createdBy'], ['users.userId'], ),
    sa.ForeignKeyConstraint(['updatedBy'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('configId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configurations')
    # ### end Alembic commands ###
