"""Modifiquei o book para aceitar campos nulos

Revision ID: 3ca3cfeac91f
Revises: 
Create Date: 2024-09-03 21:07:03.714624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca3cfeac91f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('authorName',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('publisherName',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('publishedDate',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('publishedDate',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('publisherName',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('authorName',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
