"""Estrutura do banco com novas tabelas e alteração de algumas colunas na tabela Alunos. Nomes de tabelas colocados no plural

Revision ID: 5ff650965de4
Revises: 
Create Date: 2024-07-03 22:05:33.871157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff650965de4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livro')
    op.drop_table('palavraChave')
    op.drop_table('emprestimo')
    op.drop_table('aluno')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('idAluno', sa.INTEGER(), nullable=False),
    sa.Column('nomeAluno', sa.VARCHAR(), nullable=False),
    sa.Column('telefoneAluno', sa.VARCHAR(), nullable=True),
    sa.Column('dtNascimento', sa.DATE(), nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=11), nullable=True),
    sa.Column('rg', sa.VARCHAR(length=10), nullable=True),
    sa.Column('serieTurma', sa.VARCHAR(), nullable=False),
    sa.Column('nomeResponsavel1', sa.VARCHAR(), nullable=True),
    sa.Column('telefoneResponsavel1', sa.VARCHAR(), nullable=True),
    sa.Column('nomeResponsavel2', sa.VARCHAR(), nullable=True),
    sa.Column('telefoneResponsavel2', sa.VARCHAR(), nullable=True),
    sa.Column('observacao', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('idAluno')
    )
    op.create_table('emprestimo',
    sa.Column('idEmprestimo', sa.INTEGER(), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=False),
    sa.Column('dataEmprestimo', sa.DATE(), nullable=False),
    sa.Column('dataDevolucao', sa.DATE(), nullable=False),
    sa.Column('aluno_id', sa.INTEGER(), nullable=False),
    sa.Column('livro_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.idAluno'], ),
    sa.ForeignKeyConstraint(['livro_id'], ['livro.idLivro'], ),
    sa.PrimaryKeyConstraint('idEmprestimo')
    )
    op.create_table('palavraChave',
    sa.Column('idPalavra', sa.INTEGER(), nullable=False),
    sa.Column('palavra', sa.VARCHAR(), nullable=False),
    sa.Column('livro_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['livro_id'], ['livro.idLivro'], ),
    sa.PrimaryKeyConstraint('idPalavra')
    )
    op.create_table('livro',
    sa.Column('idLivro', sa.INTEGER(), nullable=False),
    sa.Column('nomeLivro', sa.VARCHAR(), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=False),
    sa.Column('nomeAutor', sa.VARCHAR(), nullable=False),
    sa.Column('nomeEditora', sa.VARCHAR(), nullable=False),
    sa.Column('dataPublicacao', sa.DATE(), nullable=False),
    sa.Column('dtAquisicao', sa.DATE(), nullable=True),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('idLivro')
    )
    # ### end Alembic commands ###
