"""Renamed configuration table to config

Revision ID: a80a1b057f18
Revises: b7870675d78f
Create Date: 2026-02-18 14:10:39.335192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a80a1b057f18'
down_revision = 'b7870675d78f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('configurations', 'config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('config', 'configurations')
    # ### end Alembic commands ###
