"""Added cancelled status and notes to Loan

Revision ID: b1d030a823a8
Revises: 3ca3cfeac91f
Create Date: 2026-02-18 13:55:37.346059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d030a823a8'
down_revision = '3ca3cfeac91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initialNote', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('finalNote', sa.Text(), nullable=True))
    
    # commit transaction so we can run outside of transaction block if needed (for some postgres versions)
    # op.execute("COMMIT") 
    # Add new value to enum
    op.execute("ALTER TYPE statusloan ADD VALUE 'CANCELLED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('finalNote')
        batch_op.drop_column('initialNote')

    # ### end Alembic commands ###
